steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/flask-gcs-app', '.']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/flask-gcs-app']
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: 'gcloud'
  args: ['run', 'deploy', 'flask-gcs-app', '--image', 'gcr.io/$PROJECT_ID/flask-gcs-app', '--platform', 'managed', '--region', 'us-central1', '--allow-unauthenticated']
images:
- 'gcr.io/$PROJECT_ID/flask-gcs-app'
